name: Android CI

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Build and run tests
      run: ./gradlew build
      env:
        ORG_GRADLE_PROJECT_ci: 1

    - name: Log checksums
      run: sha256sum native-utils/build/outputs/aar/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: native-utils-aar
        path: native-utils/build/outputs/aar

    - name: Publish to GitHub Packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
      env:
        ORG_GRADLE_PROJECT_ci: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
